require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Readyrental' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Flipper disabled: incompatible with Xcode 16+/Clang 17+ (C++ Folly build errors).
    # Not needed for release/sideload builds anyway.
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ReadyrentalTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Xcode 16/26 compatibility fixes for all pod targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Xcode 26 requires iOS 12.0+; bump all pods to 13.0 to match app
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        # Force C++17 for Yoga/Folly (Xcode 26 defaults to C++20 which breaks these)
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        # Silence non-fatal warnings that become errors on newer Clang
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        # Fix for M1/arm64 builds
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      end
    end
  end
end
